FROM node:20

WORKDIR /test_playground/frontend
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY . .

# RUN chown -R node:node /test_playground/frontend
RUN chsh -s /bin/bash node

ARG APP_ENV
ENV NEXT_PUBLIC_APP_ENV=$APP_ENV

RUN npm run build

USER node