FROM node:20

WORKDIR /test_playground/frontend
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY . .

# RUN chown -R node:node /test_playground/frontend
RUN chsh -s /bin/bash node

ENV NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL
RUN npm run build

USER node