services:
  k6:
    build:
      context: ./loadtest/k6
      dockerfile: Dockerfile.k6

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6db
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
    user: "0"
    depends_on:
      - influxdb
volumes:
  next_volume:
