services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.db
    image: db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  server:
    build:
      context: ./backend
      dockerfile: ${BACKEND_DOCKERFILE:-Dockerfile}
    image: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE:-backend.settings}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - JWT_VERIFYING_KEY=${JWT_VERIFYING_KEY}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV:-development}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ${FRONTEND_DOCKERFILE:-Dockerfile.ci}
      args:
        APP_ENV: ${APP_ENV}
    image: frontend
    command: npm run start
    ports:
      - 3000:3000
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - server

  testrunner:
    build:
      context: ./
      dockerfile: ./loadtest/k6/container/${TESTRUNNER_DOCKERFILE:-Dockerfile.testrunner}
      args:
        APP_ENV: ${APP_ENV}
    image: testrunner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9323:9323
    environment:
      - TEST_URL=${TEST_URL}
      - APP_ENV=${APP_ENV}
      - SET_CRONJOBS=${SET_CRONJOBS:-0} #disabled by default -> set to local|cloud
      - PLAYWRIGHT_HTML_HOST=0.0.0.0
