import { Inter } from "next/font/google";
import "./global-styles.css";
import React from "react";
import Navigation from "@/components/Navigation";
import { UserProvider } from "@/context/user";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <UserProvider>
          <Navigation></Navigation>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
