name: Tear down AWS resources.

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ci, staging, production] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy
        run: |
          echo "Destroying ${{ matrix.environment }}"
          cd terraform/${{ matrix.environment }}
          terraform init
          terraform destroy -auto-approve