name: Tear down AWS resources.

on:
  workflow_dispatch:

env:
  TF_VAR_DB_HOST: "placeholder"
  TF_VAR_DJANGO_SECRET_KEY: "placeholder"
  TF_VAR_JWT_SIGNING_KEY: "placeholder"
  TF_VAR_JWT_VERIFYING_KEY: "placeholder"
  TF_VAR_POSTGRES_DB: "placeholder"
  TF_VAR_POSTGRES_PASSWORD: "placeholder"
  TF_VAR_POSTGRES_USER: "placeholder"
  TF_VAR_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}
  TF_VAR_AWS_REPO: ${{ secrets.AWS_REPO}}
  TF_VAR_environment: "placeholder"
  TF_VAR_DJANGO_ENV: "placeholder"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ci, staging, production] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.7"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Destroy
        run: |
          echo "Destroying ${{ matrix.environment }}"
          cd terraform/${{ matrix.environment }}
          terraform init
          terraform destroy -auto-approve