name: Terraform workflow

on:
  push:
    branches: ["pipes"]
    paths: ["terraform/**"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print current directory
        run: |
          echo "Current working directory: $PWD"
          ls -al $PWD

      - name: Run terrascan
        run: cd terraform/tests && terraform test

      - name: Run terrascan
        run: make terrascan_ci
