name: Terraform workflow

on:
  push:
    branches: ["pipes"]
    paths: ["terraform/**"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run terrascan
        run: make terrascan_ci
